1. Import numpy as np and see the version

In [2]:
import numpy as np
np.__version__

'1.22.2'

2. How to create a 1D array?

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. How to create a boolean array?

-> We can create bool type that use dtype keyword

In [7]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. How to extract items that satisfy a given condition from 1D array?

-> Create an array of five values evenly spaced between 0 and 1

-> Using arange(start,stop,step) method can creat the reuslt that the example which we debug. 

In [22]:
arr = np.array(range(0,10))
arr[1::2]

array([1, 3, 5, 7, 9])

5. How to replace items that satisfy a condition with another value in numpy array?

In [20]:
arr[1::2] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


6. How to replace items that satisfy a condition without affecting the original array?

In [23]:
arr_sub = arr.copy()
arr_sub[1::2] = -1
print(arr_sub)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [24]:
# The solution which in web page
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

7. How to reshape an array?

-> reshape(row,col). When we use this method, if we put -1 in col location, col is set under the influence of row and original arr shape.

In [26]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. How to stack two arrays vertically?
(vertically = 수직으로)

-> use vstack or concatenate

In [31]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.vstack([a,b])


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. How to stack two arrays horizontally?
(horizontally = 가로로)

In [32]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. How to generate custom sequences in numpy without hardcoding?

-> Have to study np.r_ and repeat, tile command.

In [35]:
x10 = np.array([1,2,3])
np.r_[np.repeat(x10, 3), np.tile(x10, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])