1. Import numpy as np and see the version

In [3]:
import numpy as np
np.__version__

'1.22.2'

2. How to create a 1D array?

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. How to create a boolean array?

-> We can create bool type that use dtype keyword

In [7]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

4. How to extract items that satisfy a given condition from 1D array?

-> Create an array of five values evenly spaced between 0 and 1

-> Using arange(start,stop,step) method can creat the reuslt that the example which we debug. 

In [22]:
arr = np.array(range(0,10))
arr[1::2]

array([1, 3, 5, 7, 9])

5. How to replace items that satisfy a condition with another value in numpy array?

In [20]:
arr[1::2] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


6. How to replace items that satisfy a condition without affecting the original array?

In [23]:
arr_sub = arr.copy()
arr_sub[1::2] = -1
print(arr_sub)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [24]:
# The solution which in web page
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

7. How to reshape an array?

-> reshape(row,col). When we use this method, if we put -1 in col location, col is set under the influence of row and original arr shape.

In [26]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. How to stack two arrays vertically?
(vertically = 수직으로)

-> use vstack or concatenate

In [31]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.vstack([a,b])


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

9. How to stack two arrays horizontally?
(horizontally = 가로로)

In [32]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

10. How to generate custom sequences in numpy without hardcoding?

-> Have to study np.r_ and repeat, tile command.

In [35]:
x10 = np.array([1,2,3])
np.r_[np.repeat(x10, 3), np.tile(x10, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

11. How to get the common items between two python numpy arrays?

In [5]:
a11 = np.array([1,2,3,2,3,4,3,4,5,6])
b11 = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a11,b11)

array([2, 4])

12. How to remove from one array those items that exist in another?

In [12]:
a12 = np.array([1,2,3,4,5])
b12 = np.array([5,6,7,8,9])
np.setdiff1d(a12,b12)

array([1, 2, 3, 4])

13. How to get the positions where elements of two arryas match?

-> where = 열으로 반환

-> argwhere = 행으로 반환

In [17]:
a13 = np.array([1,2,3,2,3,4,3,4,5,6])
b13 = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a13==b13)

(array([1, 3, 5, 7], dtype=int64),)

14. How to extract all numbers between a given range from a numpy array?

In [20]:
a14 = np.array([2, 6, 1, 9, 10, 3, 27])
a14[(a14>=5) & (a14<=10)]

array([ 6,  9, 10])

15. How to make a python function that handles scalars to work on numpy arrays?

In [5]:
def max(a,b):
    if a >= b:
        return a
    else:
        return b;

pair_max = np.vectorize(max, otypes=[float])

a = np.array([5,7,9,8,6,4,5])
b = np.array([6,3,4,8,9,7,1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

16. How to swap two columns in a 2D numpy array?

In [8]:
arr = np.arange(9).reshape(3,3)
arr
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

17. How to swap two rows in a 2D numpy array?

In [9]:
arr17 = np.arange(9).reshape(3,3)
arr17
arr17[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

18. How to reverse the rows of a 2D array?

In [14]:
arr18 = np.arange(9).reshape(3,3)
arr18
arr18[::-1, :]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

19. How to reverse the columns of a 2D array?

In [15]:
arr19 = np.arange(9).reshape(3,3)
arr19[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

20. How to create a 2D array containing random floats between 5 and 10?

In [19]:
arr20 = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
arr20

array([[7.76468867, 5.28407156, 5.61657215],
       [9.58267673, 7.91519089, 5.82376399],
       [6.83784389, 6.73094002, 6.97204065],
       [7.93108641, 6.81767478, 7.84384558],
       [5.31076954, 6.9219234 , 6.52099018]])