In [ ]:
import numpy as np

# **Numpy**



> **행 = 가로줄 개수(x축 값의 개수)**


> **열 = 세로줄 개수(y축 값의 개수)**






## 선언 방식


1.   np.array([1, 2, 3, 4, 5])
2.   np.zeros, np.ones, np.full, np.arange, np.linspace, np.empty, np.eye
3.   np.random.~

### 1.np.array


> np.array 항목에 int와 float을 작성했을 때 정보 손실을 최소화하는 방법으로 compile.



In [ ]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [ ]:
np.array([3.14, 2, 4, 5])

array([3.14, 2.  , 4.  , 5.  ])

In [ ]:
np.array([1, 2, 3, 4, 5], dtype='float32') # 이처럼 dtype을 사용하여 Numpy Array의 데이터 타입을 변경 가능

array([1., 2., 3., 4., 5.], dtype=float32)

In [ ]:
np.array([range(i, i+3) for i in [2,4,6]])
# < 구현 방식 - list comprehension >
# np.array([range(2, 5)])
# np.array([range(4,7)])
# np.array([range(6,9)])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### 2. 편리한 선언 도구들

In [ ]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,5), dtype=float) # 3행 5열

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,4), 3.14) # 3행 4열

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.arange(0, 20, 2) # np.arange(start, stop, step)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0, 1, 5) # 0과 1를 5등분

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.eye(3) # 정방 행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty(3)

array([1., 1., 1.])

#### np.random.~


1.   np.random.random - 0과 1 사이의 숫자를 무작위 출력
2.   np.random.randint - 지정한 범위 사이의 값을 int형으로 무작위 출력
3.   np.random.normal(avg, 표준 편차, shape) - 정규 분포
4.   np.random.seed - 항상 똑같은 random 값 출력을 위해 사용
5.   np.random.RandomState(num) - num은 일종의 RandomState의 번호.
> 이를 지정하지 않을 경우, 여러개의 RandomState 사용시 모두 같은 random 값 출력


In [ ]:
np.random.random((3,3))

array([[0.36942919, 0.04999422, 0.8210913 ],
       [0.06370908, 0.99651334, 0.73394383],
       [0.88997669, 0.35460493, 0.45826375]])

In [ ]:
np.random.normal(5, 2, (3,3))

array([[9.83635233, 3.7953235 , 4.88992361],
       [9.03438481, 3.21141888, 6.25228999],
       [4.59189679, 5.50402554, 4.36119836]])

In [ ]:
np.random.randint(0, 10, (3,3))

array([[5, 9, 7],
       [7, 6, 3],
       [9, 5, 8]])

In [ ]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,3))
x3 = np.random.randint(10, size=(3,4,5))

## 연산자


1.   Attributes of array - ndim, shape, size, dtype, itemsize, nbytes
2.   Indexing
3.   Slicing
4.   Reshape
5.   Concatenation and Splitting


### 1. Attributes of Array

In [ ]:
print("x3 ndim : ", x3.ndim)
print("x3 shpae : ", x3.shape)
print("x3 size : ", x3.size)
print("x3 dtype : ", x3.dtype)
print("x3 itemsize : ", x3.itemsize, "bytes")
print("x3 nbytes : ", x3.nbytes, "bytes") # nbytes = itemsize * size

x3 ndim :  3
x3 shpae :  (3, 4, 5)
x3 size :  60
x3 dtype :  int64
x3 itemsize :  8 bytes
x3 nbytes :  480 bytes


### 2. Indexing

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
print(x1[0])
print(x1[1])
print(x1[5])
print(x1[-1])

5
0
9
9


In [ ]:
print(x2[0,0])
print(x2[2,0])
x2[0, 0] = 12
print(x2[0,0])

3
8
12


#### Fancy Indexing


*   Fancy Indexing 결과 shape은 index array의 shape을 따름. 즉, 참조하는 본래 array의 shape이 아님.



In [ ]:
rand = np.random.RandomState(42)

fcy = rand.randint(100, size=10)
print(fcy)

[51 92 14 71 60 20 82 86 74 74]


In [ ]:
idx = [3, 7, 4]
fcy[idx]

array([71, 86, 60])

In [ ]:
idx2 = np.array([[3,7],
                 [4,5]])
fcy[idx2]
print("fcy shape : ", fcy.shape)
print("idx2 shape : ", idx2.shape)
print("fcy[idx2] shape : ", fcy[idx2].shape)

fcy shape :  (10,)
idx2 shape :  (2, 2)
fcy[idx2] shape :  (2, 2)


In [ ]:
sec_dim = np.arange(1,13).reshape((3,4))
sec_dim

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
row = np.array([0,1,2])
col = np.array([2,1,3])
sec_dim[row, col] # [0,2], [1,1], [2,3] 이 배열로 출력됨.

array([ 3,  6, 12])

### 3. Slicing


> array_name[start:stop:step] - step이 음수인 경우, 역순 array 생성 & start, stop의 default 서로 바뀜

> 대량의 데이터를 slice하여 변경하면 원본도 변경된다 (copy를 이용해 문제해결)







#### 1차원 배열

In [ ]:
one = np.arange(10)
one

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one[:5] # 처음 ~ 5번째 원소

array([0, 1, 2, 3, 4])

In [ ]:
one[5:] # 5번 인덱스 ~ 마지막

array([5, 6, 7, 8, 9])

In [ ]:
one[4:7] # 4번 인덱스 ~ 7번째 원소

array([4, 5, 6])

In [ ]:
one[::2] # 2칸씩 띄엄띄엄 출력

array([0, 2, 4, 6, 8])

In [ ]:
one[1::2] # 1번 인덱스부터 마지막까지 2칸씩 띄어서 출력

array([1, 3, 5, 7, 9])

In [ ]:
one[::-1] # 역순 배열

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
one[5::-2] # (역순 기준)5번째 원소 ~ 마지막까지 2칸씩 띄어서 출력 

array([5, 3, 1])

#### 2차원 배열

In [ ]:
two = np.arange(1, 13)
two = two.reshape((3,4))
two

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
two[:2, :3] # 두 개의 행, 세 개의 열

array([[1, 2, 3],
       [5, 6, 7]])

In [ ]:
two[:3, ::2] # 세 개의 행, 열은 두칸 씩 띄움.

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [ ]:
two[::-1, ::-1] # 행과 열 역순

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [ ]:
print(two[:, 0]) # 모든 행에서 0번 인덱스의 열만 출력

[1 5 9]


In [ ]:
print(two[0, :]) # 0번 인덱스 행의 열 모두 출력
# = print(two[0])

[1 2 3 4]


In [ ]:
t_sub = two[:2, :2]
print(t_sub)

[[1 2]
 [5 6]]


In [ ]:
t_sub[0, 0] = 99
print(t_sub)
print(two)

[[99  2]
 [ 5  6]]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
t_sub[0, 0] = 1 # two 값 복구

In [ ]:
t_sub_copy = two[:2, :2].copy()
print('< Copy_before > \n', t_sub_copy)
t_sub_copy[0,0] = 99
print('< Copy_after_modify > \n', t_sub_copy)
print(' < The original data > \n', two)

< Copy_before > 
 [[1 2]
 [5 6]]
< Copy_after_modify > 
 [[99  2]
 [ 5  6]]
 < The original data > 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 4. Reshape


*   newaxis = newaxis를 작성한 위치의 shape값이 1증가( 한 차원만큼 증가 )



In [ ]:
re1 = np.arange(1,7)
print(re1.shape)
re1.reshape((2,3))

(6,)


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
re1[np.newaxis, :]
test = re1.reshape((2,3))
print("Original_test\n", test)
print("After use np.newaxis\n", test[:, np.newaxis])

Original_test
 [[1 2 3]
 [4 5 6]]
After use np.newaxis
 [[[1 2 3]]

 [[4 5 6]]]


In [ ]:
re1[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### 5. 붙이기(Concatenation) and Splitting


#### Concatenation(배열끼리의 연산)

1.   concatenate([a,b]) - a 뒤에 b 붙임***(axis 개념 등장)***
2.   vstack - 한 행의 구성 개수가 같을 때 사용 가능하며 붙이고자 하는 배열이 행으로 추가됨.
3.   hstack - 열의 구성 개수가 같을 때 사용 가능



In [ ]:
con1 = np.array([1,2,3])
con2 = np.array([3,2,1])
np.concatenate([con1,con2])

array([1, 2, 3, 3, 2, 1])

In [ ]:
grid = np.array([[1,2,3],
                 [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([grid,grid]) # default - axis = 0 (행이 추가됨)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([grid, grid], axis=1) # axis = 1 (열이 추가됨)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### Splitting

In [ ]:
sp = [1,2,3, 99, 99, 3, 2, 1]
s1, s2, s3 = np.split(sp, [3,5]) # sp 원소들을 3번 인덱스까지 묶고, 5번 인덱스까지 묶음으로서 나눔
print(s1, s2, s3)

[1 2 3] [99 99] [3 2 1]


## 수학적 계산


1.   Arithmetic
2.   Aggregates(집계)
3.   etc.



### 1. Arithmetic



#### add, subtract, negative, multiply, divide, power,mod

In [ ]:
amt = np.arange(4)
print("Original : ", amt)
print("Add : ", np.add(amt, 10))
print("Subtraction : ", np.subtract(amt, 10))
print("Negative : ", np.negative(amt))
print("Multiply : ", np.multiply(amt,10))
print("Divide : ", np.divide(amt, 10))
print("Power : ", np.power(amt, 2))
print("Mod : ", np.mod(amt, 10))

Original :  [0 1 2 3]
Add :  [10 11 12 13]
Subtraction :  [-10  -9  -8  -7]
Negative :  [ 0 -1 -2 -3]
Multiply :  [ 0 10 20 30]
Divide :  [0.  0.1 0.2 0.3]
Power :  [0 1 4 9]
Mod :  [0 1 2 3]


In [ ]:
# np.(sin/cos/tan/arcsin/arccos/arctan) 가능
# np.(logn/exp) 가능

#### Specifying output( for 사용 x )

In [ ]:
t1 = np.arange(5)
t2 = np.empty(5)
t3 = np.zeros(10)
np.multiply(t1, 10, out=t2)
np.power(2, t1, out=t3[::2])
print(t2)
print(t3)

[ 0. 10. 20. 30. 40.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


### 2. Aggregates

#### Reduce - 반복 결과 줄이기

In [ ]:
rd = np.arange(1, 6)
print("Original : ", rd)
print("Use add and reduce method : ", np.add.reduce(rd))
print("Use multiply and reduce method : ", np.multiply.reduce(rd))

Original :  [1 2 3 4 5]
Use add and reduce method :  15
Use multiply and reduce method :  120


#### Accumulate - 중간 결과를 저장

In [ ]:
acm = np.arange(1,6)
print("Original : ", acm)
print("Use add and accumulate method : ", np.add.accumulate(acm))
print("Use multiply and accumulate method : ", np.multiply.accumulate(acm))

Original :  [1 2 3 4 5]
Use add and accumulate method :  [ 1  3  6 10 15]
Use multiply and accumulate method :  [  1   2   6  24 120]


#### Other aggregation functions (sum, mean, prod, min, max, etc.)

In [ ]:
value = np.arange(1,101)
print("Value : ", value)
print("Sum of value : ", np.sum(value))
print("Minimum value : ", np.min(value))
print("Minimum index value : ", value.argmin())
print("Maximum value : ", np.max(value))
print("Maximum index value : ", value.argmax())
print("Mean value : ", value.mean())
print("Std value : ", value.std()) # 표준편차 = sqrt(분산)
print("Var value : ", value.var()) # 분산 = (값 - 평균)^2의 합 / 값의 개수
print("Median value : ", np.median(value))

Value :  [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Sum of value :  5050
Minimum value :  1
Minimum index value :  0
Maximum value :  100
Maximum index value :  99
Mean value :  50.5
Std value :  28.86607004772212
Var value :  833.25
Median value :  50.5


In [ ]:
multi_value = np.arange(1,13).reshape((3,4))
print("< Multi_value >")
print(multi_value)
print("Sum of Multi_value : ", multi_value.sum())
print("Minimum of Multi_value in row(x축) : ", multi_value.min(axis=0))
print("Minimum of Multi_value in colum(y축) : ", multi_value.min(axis=1))
print("Maximum of Multi_value in row(x축) : ", multi_value.max(axis=0))
print("Maximum of Multi_value in colum(y축) : ", multi_value.max(axis=1))

< Multi_value >
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sum of Multi_value :  78
Minimum of Multi_value in row(x축) :  [1 2 3 4]
Minimum of Multi_value in colum(y축) :  [1 5 9]
Maximum of Multi_value in row(x축) :  [ 9 10 11 12]
Maximum of Multi_value in colum(y축) :  [ 4  8 12]


In [ ]:
three_demensions = np.arange(1, 61).reshape((3,4,5))
print("< Three Demensions >")
print(three_demensions)
print("Sum of three_demensions : ", three_demensions.sum())
print()
print("< Minimum of tree_demensions in axis = 0 >")
print(three_demensions.min(axis=0))
print()
print("< Minimum of tree_demensions in axis = 1 >")
print(three_demensions.min(axis=1))
print()
print("< Minimum of tree_demensions in axis = 2 >")
print(three_demensions.min(axis=2))
print()
print("< Maximum of tree_demensions in axis = 0 >")
print(three_demensions.max(axis=0))
print()
print("< Maximum of tree_demensions in axis = 1 >")
print(three_demensions.max(axis=1))
print()
print("< Maximum of tree_demensions in axis = 2 >")
print(three_demensions.max(axis=2))

< Three Demensions >
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]
Sum of three_demensions :  1830

< Minimum of tree_demensions in axis = 0 >
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

< Minimum of tree_demensions in axis = 1 >
[[ 1  2  3  4  5]
 [21 22 23 24 25]
 [41 42 43 44 45]]

< Minimum of tree_demensions in axis = 2 >
[[ 1  6 11 16]
 [21 26 31 36]
 [41 46 51 56]]

< Maximum of tree_demensions in axis = 0 >
[[41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]

< Maximum of tree_demensions in axis = 1 >
[[16 17 18 19 20]
 [36 37 38 39 40]
 [56 57 58 59 60]]

< Maximum of tree_demensions in axis = 2 >
[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]


##

## 논리 연산

In [ ]:
bol = np.array([1, 2, 3, 4, 5])
print("Which value < 3 in bol : ", bol<3)
print("Which value > 3 in bol : ", bol>3)
print("Which value <= 3 in bol : ", bol<=3)
print("Which value >= 3 in bol : ", bol>=3)
print("Which value != 3 in bol : ", bol != 3)
print("Which value == 3 in bol : ", bol == 3)
print("Which value satisfied (2 * bol) == (bol ** 2) in bol : ", (2*bol)==(bol**2))
print("How many values are true in (bol < 4)?", np.count_nonzero(bol< 4),"개")

Which value < 3 in bol :  [ True  True False False False]
Which value > 3 in bol :  [False False False  True  True]
Which value <= 3 in bol :  [ True  True  True False False]
Which value >= 3 in bol :  [False False  True  True  True]
Which value != 3 in bol :  [ True  True False  True  True]
Which value == 3 in bol :  [False False  True False False]
Which value satisfied (2 * bol) == (bol ** 2) in bol :  [False  True False False False]
How many value's are true in (bol < 4)? 3 개


In [ ]:
bol2 = np.arange(1,13).reshape((3,4))
print("< bol2 value >")
print(bol2)
print("How many values are true in (bol2<8)?")
print("Use sum : ", np.sum(bol2<8))
print("Use count_nonzero : ", np.count_nonzero(bol2<8))
# sum 은 axis 를 통해 row와 colum 각각 계산이 가능하다.
print("Row count : ", np.sum(bol2<8, axis=0)) # axis = 0 으로하면, 결과값의 개수가 한 row에 존재하는 col의 개수.
print("Col count : ", np.sum(bol2<8, axis=1))

< bol2 value >
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
How many values are true in (bol2<8)?
Use sum :  7
Use count_nonzero :  7
Row count :  [2 2 2 1]
Col count :  [4 3 0]


### Any - 적어도 하나의 원소가 만족

In [ ]:
print("< bol >")
print(bol)
print("np.any(bol>3) : ", np.any(bol>3))
print("np.any(bol<0) : ", np.any(bol<0))
print("< bol2 >")
print(bol2)
print("np.any(bol2>8, axis=0) : )", np.any(bol2>8, axis=0))
print("np.any(bol2>8, axis=1) ; ", np.any(bol2>8, axis=1))
print("np.any(bol2<0, axis=0) : ", np.any(bol2<0, axis=0))
print("np.any(bol2<0, axis=1) : ", np.any(bol2<0, axis=1))

< bol >
[1 2 3 4 5]
np.any(bol>3) :  True
np.any(bol<0) :  False
< bol2 >
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
np.any(bol2>8, axis=0) : ) [ True  True  True  True]
np.any(bol2>8, axis=1) ;  [False False  True]
np.any(bol2<0, axis=0) :  [False False False False]
np.any(bol2<0, axis=1) :  [False False False]


### All - 모든 원소가 만족

In [ ]:
print("< bol >")
print(bol)
print("np.all(bol<6) : ", np.all(bol<6))
print("np.all(bol==3) : ", np.all(bol==3))
print("< bol2 >")
print(bol2)
print("np.all(bol2>8, axis=0) : )", np.all(bol2>8, axis=0))
print("np.all(bol2>8, axis=1) ; ", np.all(bol2>8, axis=1))
print("np.all(bol2<0, axis=0) : ", np.all(bol2<0, axis=0))
print("np.all(bol2<0, axis=1) : ", np.all(bol2<0, axis=1))

< bol >
[1 2 3 4 5]
np.all(bol>3) :  True
np.all(bol<0) :  False
< bol2 >
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
np.all(bol2>8, axis=0) : ) [False False False False]
np.all(bol2>8, axis=1) ;  [False False  True]
np.all(bol2<0, axis=0) :  [False False False False]
np.all(bol2<0, axis=1) :  [False False False]


### 비트 연산자 ( & | ^ ~ )

In [ ]:
print("bol")
print(bol)
print("bol > 1 : ", bol>1)
print("bol < 5 : ", bol<5)
print("(bol>1) & (bol<5) : ", (bol>1) & (bol<5))
print("Count of terms that satisfied (bol>1) & (bol<5) : ", np.sum((bol>1) & (bol<5)))

bol
[1 2 3 4 5]
bol > 1 :  [False  True  True  True  True]
bol < 5 :  [ True  True  True  True False]
(bol>1) & (bol<5) :  [False  True  True  True False]
Sum of terms that (bol>1) & (bol<5) :  3


## sort - 정렬

In [ ]:
nonsort = np.array([5, 2, 4, 1, 3])
print("Before sort : ", nonsort)
print("After sort : ", np.sort(nonsort))
# np.sort(nonsort) 사용하면 그 순간이 끝. 즉, print(nonsort)를 해보면 원본이 나옴
# 원본 자체를 sort 하려면, nonsort.sort() 사용

Before sort :  [5 2 4 1 3]
After sort :  [1 2 3 4 5]


In [ ]:
print("nonsort : ", nonsort)
print("Index : ", np.argsort(nonsort))
s_i = np.argsort(nonsort)
print("nonsort[s_i] : ", nonsort[s_i])

nonsort :  [5 2 4 1 3]
Index :  [3 1 4 2 0]
nonsort[s_i] :  [1 2 3 4 5]


In [ ]:
nonsort2 = np.random.randint(1, 10, (3,4))
print("< nonsort 2 >")
print(nonsort2)
print("Sort axis = 0")
print(np.sort(nonsort2,axis=0)) # 행 방향 진행(세로)
print("Sort axis = 1")
print(np.sort(nonsort2,axis=1)) # 열 방향 진행(가로)

< nonsort 2 >
[[5 4 1 9]
 [8 2 4 2]
 [3 5 8 2]]
Sort axis = 0
[[3 2 1 2]
 [5 4 4 2]
 [8 5 8 9]]
Sort axis = 1
[[1 4 5 9]
 [2 2 4 8]
 [2 3 5 8]]


#### partition - 가장 작은 값 k를 array 왼편에 배치

In [ ]:
pt_array = np.array([7, 2, 3, 1, 6, 5, 4])
print("pt_array : ", pt_array)
print("Use partition(pt_array, 3) : ", np.partition(pt_array, 3))
pt_array2 = nonsort2.copy()
print("< pt_array 2 >")
print(pt_array2)
print("Use partition(pt_array2, 2 ,axis=0)") # 행 방향 진행(행 방향이 세로)
print(np.partition(pt_array2, 2, axis=0))
print("Use partition(pt_array2, 3 ,axis=1)") # 열 방향 진행(열 방향이 가로)
print(np.partition(pt_array2, 3, axis=1))

pt_array :  [7 2 3 1 6 5 4]
Use partition(pt_array, 3) :  [2 1 3 4 6 5 7]
< pt_array 2 >
[[5 4 1 9]
 [8 2 4 2]
 [3 5 8 2]]
Use partition(pt_array2, 2 ,axis=0)
[[3 2 1 2]
 [5 4 4 2]
 [8 5 8 9]]
Use partition(pt_array2, 3 ,axis=1)
[[1 4 5 9]
 [2 2 4 8]
 [2 3 5 8]]
