In [10]:
#base
import numpy as np
size, value, start, end, step, count, mean, std=10, 5, 0, 20, 2, 5, 0, 1
shape=(3,5)

### Understanding Data Types

numpy array는 fixed-type array이다.

정수와 실수가 혼합되면 upcast (정수→실수) 되며, dtype keyword로 지정할 수 있다.

dtype : int32/64, uint32/64, float32/64, complex64/128, ...

다차원 배열 생성이 가능하다.

In [3]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Creating Arrays

In [11]:
np.zeros(size) #0으로 채워진 array 생성
np.ones(size) #1로 채워진 array 생성
np.full(size, value) #value로 채워진 array 생성
np.arange(start, end, step) #range와 비슷함
np.linspace(start, end, count) #start~end을 일정 간격으로 분할
np.random.random(size) #0과 1 사이의 균일 분포된 랜덤 실수
np.random.normal(mean, std, size) #정규분포에 따른 랜덤 실수
np.random.randint(start, end, size) #start~end-1 랜덤 정수
np.eye(size) #정방행렬
np.empty(size) #size만큼의 공간 할당. 데이터는 그 주소값의 데이터를 따름

array([-1.62186125e+00,  1.97801237e-04,  8.26779342e-01,  1.14842025e+00,
       -9.98727049e-01, -1.61833487e+00,  1.95767325e-01,  1.29218530e+00,
        4.62420588e-01,  1.11776126e-01])

### Basics of Numpy Arrays

In [14]:
x=np.random.randint(start, end, shape)

##### Attributes



몇차원, 각 차원 원소 개수, 크기, 원소 자료형, 원소 사이즈, 전체 사이즈

In [18]:
x.ndim, x.shape, x.size, x.dtype, x.itemsize, x.nbytes 

(2, (3, 5), 15, dtype('int32'), 4, 60)

##### Indexing



0부터 시작하며 []을 사용한다. 음수도 가능하다. 다차원에서는 comma를 사용하여 차원을 구분한다.

##### Slicing



x[start:end:step] default : start=0, stop=size, step=1

다차원에서는 comma를 사용하여 차원을 구분한다.

slice subarray는 원본의 일부이므로 subarray를 수정하면 원본도 변경된다. (copy method 이용)

##### Accessing



row, column 잘라내기 : x[:, 0], x[0, :] (row를 잘라내는 경우 empty slice 생략 가능)

##### Reshaping

In [69]:
X=np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

np.newaxis를 이용하면 한 차원 증가한다. (shape 수는 1)

In [70]:
a=np.array([1,2,3])
print(a[np.newaxis, :])
print(a[:, np.newaxis])

[[1 2 3]]
[[1]
 [2]
 [3]]


##### Concatenation & Splitting

In [29]:
a, b=np.array([1,2,3]), np.array([4,5,6])
c=np.array([[1,2,3],[4,5,6]])
d=c.copy()

In [33]:
np.concatenate([a,b]) 
#print(np.concatenate([a,b],axis=1)) 1차원 배열끼리는 axis=1 접합 불가능. vstack 이용
np.concatenate([c,d]) #vstack
np.concatenate([c,d], axis=1) #hstack

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [37]:
x=np.random.randint(start, end, size)
print(x)
print(np.split(x, [3,5])) #n번째 인덱스를 기준으로 분할. vsplit, hsplit도 있다.

[ 9  9  5  7  5  1  8  7 13 18]
[array([9, 9, 5]), array([7, 5]), array([ 1,  8,  7, 13, 18])]


### UFunc

Vectorized Operation으로 연산 속도가 빠르다.

두 array 간의 vectorized operation도 가능하다. (다차원도 가능)

out argument로 출력 장소를 지정할 수 있다.

##### unary ufuncs

add, subtract, negative, multiply, divide, floor_divide, power, mod, absolute, 삼각함수, 지수, 로그, ...

##### binary ufuncs

reduce method로 결과를 줄일 수 있다.

accumulate로 중간 결과를 저장할 수 있다.

sum, prod, cumsum, cumprod, outer(외적), inner(내적)

### Aggregations

##### Functions

sum, prod, mean, std, var, min, max, argmin, argmax, median, percentile, any, all

nan을 붙이면 배열의 NaN을 배제하고 연산한다.

axis argument로 축을 지정할 수 있다.

합계, 곱, 평균, 표준편차, 분산, 최솟값, 최댓값, 최솟값 인덱스, 최댓값 인덱스, 중앙값, 백분위 수

### Broadcasting

##### Rules of Broadcasting

1. 두 array의 차원이 다른 경우 낮은 차원의 array에서 부족한 차원 개수만큼 왼쪽에 1을 채운다.
2. 각 차원에서 그 크기가 다른 경우 차원값이 1인 것을 변경하여 일치시킨다.
3. 2가 적용되지 않는다면 Error

``M.shape=(3,2), N.shape=(3,)`` 일 경우

Rule 1에 의해 ``N.shape=(1,3)``이 되고

Rule 2에 의해 ``N.shape=(3,3)``이 되어 일치하지 않으므로 Error

### Comparisons, Masks, Boolean Logic

##### Comparisons

<, >, >=, <=, !=, ==

np.less, greater, greater_eqaul, less_eqaul, not_equal, equal

In [39]:
x=np.array([1,2,3,4,5])

In [41]:
x>3

array([False, False, False,  True,  True])

##### Boolean Arrays

In [44]:
#1의 갯수 세기
print(np.sum(x>3)) #row, column별 계산 가능
print(np.count_nonzero(x>3))

2
2


np.any, all : 하나라도 1이면 True, 모두 1이면 True

axis 지정 가능

bitwise logic operators : ``&, |, ^, ~``

``np.bitwise_and, bitwise_or, bitwise_xor, bitwise_not``

#####  Masking

In [45]:
x

array([1, 2, 3, 4, 5])

In [48]:
x[x>3], x[x<=3]

(array([4, 5]), array([1, 2, 3]))

### Fancy Indexing

##### array의 접근 방식

simple indexing ``arr[0], arr[0,1]``

slices ``arr[0:3]``

boolean masks ``arr[arr>3]``

fancy indexing ``index array 전달``

##### Fancy Indexing

결과의 shape는 index arrays의 shape를 따른다.

In [54]:
x=np.random.randint(start, end, size)

array([ 7,  0,  5, 14, 15, 15, 11, 16, 14,  0])

In [60]:
index_1d, index_2d=[2,1,0], np.array([[3,4,5],[0,1,2]])
x[index_1d]

array([5, 0, 7])

In [61]:
x[index_2d]

array([[14, 15, 15],
       [ 7,  0,  5]])

다차원의 경우 마찬가지로 comma로 차원을 구분한다.

In [68]:
x=np.arange(12).reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
row, col=np.array([0,1,2]), np.array([2,1,3])
x[row, col]

array([ 2,  5, 11])

##### Combined Indexing

In [ ]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

fancy & simple

In [72]:
X[2,[2,0,1]]

array([10,  8,  9])

fancy & slicing

In [73]:
X[1:, [2,0,1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

fancy & masking

In [74]:
mask=np.array([1,0,1,0], dtype=bool)

In [75]:
X[:, mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

##### Modifying

In [81]:
x=np.zeros(size, dtype=int)

In [82]:
i=np.array([2,1,8,4])
x[i]=-1
x

array([ 0, -1, -1,  0, -1,  0,  0,  0, -1,  0])

In [83]:
x[i]+=2
x

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 0])

### Sorting

##### ``np.sort`` & ``np.argsort``

np.sort

In [87]:
x=np.array([3,1,4,2,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [86]:
x.sort() #in-place sort
x

array([1, 2, 3, 4, 5])

np.argsort (정렬했을 때의 index)

In [88]:
np.argsort(x)

array([1, 3, 0, 2, 4], dtype=int64)

axis 지정이 가능하다.

In [89]:
x=np.random.randint(start, end, (5,6))
x

array([[ 2,  3, 14,  2,  4, 17],
       [11,  8, 18,  1,  8,  5],
       [11, 13, 18,  6,  1,  4],
       [ 2,  5,  1,  7, 16, 11],
       [17,  2,  9,  9,  8, 12]])

In [90]:
np.sort(x, axis=0) #행방향

array([[ 2,  2,  1,  1,  1,  4],
       [ 2,  3,  9,  2,  4,  5],
       [11,  5, 14,  6,  8, 11],
       [11,  8, 18,  7,  8, 12],
       [17, 13, 18,  9, 16, 17]])

In [91]:
np.sort(x, axis=1) #열방향

array([[ 2,  2,  3,  4, 14, 17],
       [ 1,  5,  8,  8, 11, 18],
       [ 1,  4,  6, 11, 13, 18],
       [ 1,  2,  5,  7, 11, 16],
       [ 2,  8,  9,  9, 12, 17]])

##### ``partitoning``

np.partition(array, k)

k>0 : k개의 가장 작은 값 왼쪽에 배치

k<0 : k개의 가장 큰 값 오른쪽에 배치

완전히 정렬되지는 않는다.

In [92]:
x=np.array([7,2,3,1,6,5,4])

In [93]:
np.partition(x,3)

array([2, 1, 3, 4, 6, 5, 7])

In [98]:
np.partition(x,1)

array([1, 2, 3, 7, 6, 5, 4])