In [1]:
import numpy as np

# **Numpy**



> **행 = 가로줄 개수(x축 값의 개수)**


> **열 = 세로줄 개수(y축 값의 개수)**






## 선언 방식


1.   np.array([1, 2, 3, 4, 5])
2.   np.zeros, np.ones, np.full, np.arange, np.linspace, np.empty, np.eye
3.   np.random.~

### 1.np.array


> np.array 항목에 int와 float을 작성했을 때 정보 손실을 최소화하는 방법으로 compile.



In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.array([3.14, 2, 4, 5])

array([3.14, 2.  , 4.  , 5.  ])

In [5]:
np.array([1, 2, 3, 4, 5], dtype='float32') # 이처럼 dtype을 사용하여 Numpy Array의 데이터 타입을 변경 가능

array([1., 2., 3., 4., 5.], dtype=float32)

In [8]:
np.array([range(i, i+3) for i in [2,4,6]])
# < 구현 방식 - list comprehension >
# np.array([range(2, 5)])
# np.array([range(4,7)])
# np.array([range(6,9)])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### 2. 편리한 선언 도구들

In [9]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3,5), dtype=float) # 3행 5열

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.full((3,4), 3.14) # 3행 4열

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [16]:
np.arange(0, 20, 2) # np.arange(start, stop, step)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.linspace(0, 1, 5) # 0과 1를 5등분

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
np.eye(3) # 정방 행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.empty(3)

array([1., 1., 1.])

#### np.random.~


1.   np.random.random - 0과 1 사이의 숫자를 무작위 출력
2.   np.random.randint - 지정한 범위 사이의 값을 int형으로 무작위 출력
3.   np.random.normal(avg, 표준 편차, shape) - 정규 분포
4.   np.random.seed - 항상 똑같은 random 값 출력을 위해 사용
5.   np.random.RandomState(num) - num은 일종의 RandomState의 번호.
> 이를 지정하지 않을 경우, 여러개의 RandomState 사용시 모두 같은 random 값 출력


In [22]:
np.random.random((3,3))

array([[0.36942919, 0.04999422, 0.8210913 ],
       [0.06370908, 0.99651334, 0.73394383],
       [0.88997669, 0.35460493, 0.45826375]])

In [24]:
np.random.normal(5, 2, (3,3))

array([[9.83635233, 3.7953235 , 4.88992361],
       [9.03438481, 3.21141888, 6.25228999],
       [4.59189679, 5.50402554, 4.36119836]])

In [25]:
np.random.randint(0, 10, (3,3))

array([[5, 9, 7],
       [7, 6, 3],
       [9, 5, 8]])

In [31]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,3))
x3 = np.random.randint(10, size=(3,4,5))

## 연산자


1.   Attributes of array - ndim, shape, size, dtype, itemsize, nbytes
2.   Indexing
3.   Slicing
4.   Reshape
5.   Concatenation and Splitting


### 1. Attributes of Array

In [34]:
print("x3 ndim : ", x3.ndim)
print("x3 shpae : ", x3.shape)
print("x3 size : ", x3.size)
print("x3 dtype : ", x3.dtype)
print("x3 itemsize : ", x3.itemsize, "bytes")
print("x3 nbytes : ", x3.nbytes, "bytes") # nbytes = itemsize * size

x3 ndim :  3
x3 shpae :  (3, 4, 5)
x3 size :  60
x3 dtype :  int64
x3 itemsize :  8 bytes
x3 nbytes :  480 bytes


### 2. Indexing

In [35]:
x1

array([5, 0, 3, 3, 7, 9])

In [38]:
print(x1[0])
print(x1[1])
print(x1[5])
print(x1[-1])

5
0
9
9


In [39]:
print(x2[0,0])
print(x2[2,0])
x2[0, 0] = 12
print(x2[0,0])

3
8
12


#### Fancy Indexing


*   Fancy Indexing 결과 shape은 index array의 shape을 따름. 즉, 참조하는 본래 array의 shape이 아님.



In [100]:
rand = np.random.RandomState(42)

fcy = rand.randint(100, size=10)
print(fcy)

[51 92 14 71 60 20 82 86 74 74]


In [101]:
idx = [3, 7, 4]
fcy[idx]

array([71, 86, 60])

In [103]:
idx2 = np.array([[3,7],
                 [4,5]])
fcy[idx2]
print("fcy shape : ", fcy.shape)
print("idx2 shape : ", idx2.shape)
print("fcy[idx2] shape : ", fcy[idx2].shape)

fcy shape :  (10,)
idx2 shape :  (2, 2)
fcy[idx2] shape :  (2, 2)


In [104]:
sec_dim = np.arange(1,13).reshape((3,4))
sec_dim

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [106]:
row = np.array([0,1,2])
col = np.array([2,1,3])
sec_dim[row, col] # [0,2], [1,1], [2,3] 이 배열로 출력됨.

array([ 3,  6, 12])

### 3. Slicing


> array_name[start:stop:step] - step이 음수인 경우, 역순 array 생성 & start, stop의 default 서로 바뀜

> 대량의 데이터를 slice하여 변경하면 원본도 변경된다 (copy를 이용해 문제해결)







#### 1차원 배열

In [40]:
one = np.arange(10)
one

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
one[:5] # 처음 ~ 5번째 원소

array([0, 1, 2, 3, 4])

In [47]:
one[5:] # 5번 인덱스 ~ 마지막

array([5, 6, 7, 8, 9])

In [45]:
one[4:7] # 4번 인덱스 ~ 7번째 원소

array([4, 5, 6])

In [49]:
one[::2] # 2칸씩 띄엄띄엄 출력

array([0, 2, 4, 6, 8])

In [50]:
one[1::2] # 1번 인덱스부터 마지막까지 2칸씩 띄어서 출력

array([1, 3, 5, 7, 9])

In [51]:
one[::-1] # 역순 배열

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [52]:
one[5::-2] # (역순 기준)5번째 원소 ~ 마지막까지 2칸씩 띄어서 출력 

array([5, 3, 1])

#### 2차원 배열

In [68]:
two = np.arange(1, 13)
two = two.reshape((3,4))
two

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
two[:2, :3] # 두 개의 행, 세 개의 열

array([[1, 2, 3],
       [5, 6, 7]])

In [69]:
two[:3, ::2] # 세 개의 행, 열은 두칸 씩 띄움.

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [70]:
two[::-1, ::-1] # 행과 열 역순

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [72]:
print(two[:, 0]) # 모든 행에서 0번 인덱스의 열만 출력

[1 5 9]


In [73]:
print(two[0, :]) # 0번 인덱스 행의 열 모두 출력
# = print(two[0])

[1 2 3 4]


In [74]:
t_sub = two[:2, :2]
print(t_sub)

[[1 2]
 [5 6]]


In [75]:
t_sub[0, 0] = 99
print(t_sub)
print(two)

[[99  2]
 [ 5  6]]
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [76]:
t_sub[0, 0] = 1 # two 값 복구

In [79]:
t_sub_copy = two[:2, :2].copy()
print('< Copy_before > \n', t_sub_copy)
t_sub_copy[0,0] = 99
print('< Copy_after_modify > \n', t_sub_copy)
print(' < The original data > \n', two)

< Copy_before > 
 [[1 2]
 [5 6]]
< Copy_after_modify > 
 [[99  2]
 [ 5  6]]
 < The original data > 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 4. Reshape


*   newaxis = newaxis를 작성한 위치의 shape값이 1증가( 한 차원만큼 증가 )



In [84]:
re1 = np.arange(1,7)
print(re1.shape)
re1.reshape((2,3))

(6,)


array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
re1[np.newaxis, :]
test = re1.reshape((2,3))
print("Original_test\n", test)
print("After use np.newaxis\n", test[:, np.newaxis])

Original_test
 [[1 2 3]
 [4 5 6]]
After use np.newaxis
 [[[1 2 3]]

 [[4 5 6]]]


In [86]:
re1[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### 5. 붙이기(Concatenation) and Splitting


#### Concatenation(배열끼리의 연산)

1.   concatenate([a,b]) - a 뒤에 b 붙임***(axis 개념 등장)***
2.   vstack - 한 행의 구성 개수가 같을 때 사용 가능하며 붙이고자 하는 배열이 행으로 추가됨.
3.   hstack - 열의 구성 개수가 같을 때 사용 가능



In [93]:
con1 = np.array([1,2,3])
con2 = np.array([3,2,1])
np.concatenate([con1,con2])

array([1, 2, 3, 3, 2, 1])

In [95]:
grid = np.array([[1,2,3],
                 [4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
np.concatenate([grid,grid]) # default - axis = 0 (행이 추가됨)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [97]:
np.concatenate([grid, grid], axis=1) # axis = 1 (열이 추가됨)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### Splitting

In [99]:
sp = [1,2,3, 99, 99, 3, 2, 1]
s1, s2, s3 = np.split(sp, [3,5]) # sp 원소들을 3번 인덱스까지 묶고, 5번 인덱스까지 묶음으로서 나눔
print(s1, s2, s3)

[1 2 3] [99 99] [3 2 1]
